### ISSUE TITLE
Upstreams - where to put them?

### ISSUE THREAD

**Issue by steklopod** [evgeniy-khist/letsencrypt-docker-compose#15]
Hi there ✌️ First of all, thank you for this project. I really need it.

I am trying to make it work with my domain + 1 subdomain. 

- I have configured `A` DNS record.
- I have upstreams and don't have static HTML files (node js frontend) and I put them in `nginx/default.conf`:

```lua

server_names_hash_bucket_size 64;

include /etc/nginx/includes/gzip.conf;

include /etc/nginx/sites/*.conf;

upstream frontend {
  server frontend:3000;
}

upstream gateway {
  server gateway:8443;
}
...
```

My `vhosts/my-domain.com.conf` looks like this:
```lua
  location / {
    proxy_pass http://frontend;
  }

  location /api {
    rewrite /api/(.*) /$1  break;
    proxy_pass http://gateway/;
  }
...
```

When I run this I got an error:
```sh
[+] Running 3/3
 ⠿ Container nginx    Recreated                                                                                                         0.2s
 ⠿ Container certbot  Recreated                                                                                                         0.2s
 ⠿ Container cron     Recreated                                                                                                         0.2s
Attaching to certbot, cron, nginx
nginx    | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx    | This is going to take a long time
nginx    | .......++*++*++*++*
nginx    | Checking configuration for MY-DOMAIN.COM
nginx    | Creating Nginx configuration file /etc/nginx/sites/MY-DOMAIN.COM.conf
nginx    | Generating dummy ceritificate for MY-DOMAIN.COM
nginx    | Generating a RSA private key
nginx    | ...............................................................+++++
nginx    | ..............................................................................+++++
nginx    | writing new private key to '/etc/nginx/sites/ssl/dummy/MY-DOMAIN.COM/privkey.pem'
nginx    | -----
nginx    | Checking configuration for kuma.MY-DOMAIN.COM
nginx    | Creating Nginx configuration file /etc/nginx/sites/kuma.MY-DOMAIN.COM.conf
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Generating dummy ceritificate for kuma.MY-DOMAIN.COM
nginx    | Generating a RSA private key
nginx    | ..+++++
nginx    | ..........+++++
nginx    | writing new private key to '/etc/nginx/sites/ssl/dummy/kuma.MY-DOMAIN.COM/privkey.pem'
nginx    | -----
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
certbot  | Obtaining the certificate for MY-DOMAIN.COM with email steklopod@gmail.com
certbot  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot  | Plugins selected: Authenticator webroot, Installer None
certbot  | Requesting a certificate for MY-DOMAIN.COM and www.MY-DOMAIN.COM
certbot  | Performing the following challenges:
certbot  | http-01 challenge for MY-DOMAIN.COM
certbot  | http-01 challenge for www.MY-DOMAIN.COM
certbot  | Using the webroot path /var/www/certbot/MY-DOMAIN.COM for all unmatched domains.
nginx    | 2022/07/14 18:00:37 [error] 26#26: *2 open() "/etc/nginx/html/.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4" failed (2: No such file or directory), client: 54.93.239.45, server: localhost, request: "GET /.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4 HTTP/1.1", host: "MY-DOMAIN.COM"
nginx    | 54.93.239.45 - - [14/Jul/2022:18:00:37 +0200] "GET /.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4 HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
certbot  | Waiting for verification...
nginx    | 2022/07/14 18:00:37 [error] 26#26: *3 open() "/etc/nginx/html/.well-known/acme-challenge/E8tmg2-SRVPigku6UMNZ-bLdKn4oNzuM1lobEysnJk4" failed (2: No such file or directory), client: 66.133.109.36, server: localhost, request: "GET /.well-known/acme-challenge/E8tmg2-SRVPigku6UMNZ-bLdKn4oNzuM1lobEysnJk4 HTTP/1.1", host: "www.MY-DOMAIN.COM"
nginx    | 66.133.109.36 - - [14/Jul/2022:18:00:37 +0200] "GET /.well-known/acme-challenge/E8tmg2-SRVPigku6UMNZ-bLdKn4oNzuM1lobEysnJk4 HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx    | 2022/07/14 18:00:37 [error] 26#26: *4 open() "/etc/nginx/html/.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4" failed (2: No such file or directory), client: 66.133.109.36, server: localhost, request: "GET /.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4 HTTP/1.1", host: "MY-DOMAIN.COM"
nginx    | 66.133.109.36 - - [14/Jul/2022:18:00:37 +0200] "GET /.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4 HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
certbot  | Challenge failed for domain MY-DOMAIN.COM
certbot  | Challenge failed for domain www.MY-DOMAIN.COM
certbot  | http-01 challenge for MY-DOMAIN.COM
certbot  | http-01 challenge for www.MY-DOMAIN.COM
certbot  | 
certbot  | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
certbot  |   Domain: MY-DOMAIN.COM
certbot  |   Type:   unauthorized
certbot  |   Detail: 185.196.21.187: Invalid response from http://MY-DOMAIN.COM/.well-known/acme-challenge/vwfwGtS_ehI6Hlzro4IN7v945UBXzWTKo9f2DV16Q_4: 404
certbot  | 
certbot  |   Domain: www.MY-DOMAIN.COM
certbot  |   Type:   unauthorized
certbot  |   Detail: 185.196.21.187: Invalid response from http://www.MY-DOMAIN.COM/.well-known/acme-challenge/E8tmg2-SRVPigku6UMNZ-bLdKn4oNzuM1lobEysnJk4: 404
certbot  | 
certbot  | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
certbot  | 
certbot  | Cleaning up challenges
certbot  | Some challenges have failed.
certbot  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
certbot  | Obtaining the certificate for kuma.MY-DOMAIN.COM without email
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
certbot  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot  | Plugins selected: Authenticator webroot, Installer None
certbot  | Requesting a certificate for kuma.MY-DOMAIN.COM and www.kuma.MY-DOMAIN.COM
certbot  | Performing the following challenges:
certbot  | http-01 challenge for kuma.MY-DOMAIN.COM
certbot  | http-01 challenge for www.kuma.MY-DOMAIN.COM
certbot  | Using the webroot path /var/www/certbot/kuma.MY-DOMAIN.COM for all unmatched domains.
certbot  | Waiting for verification...
nginx    | 2022/07/14 18:00:41 [error] 26#26: *5 open() "/etc/nginx/html/.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y" failed (2: No such file or directory), client: 18.117.253.113, server: localhost, request: "GET /.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y HTTP/1.1", host: "kuma.MY-DOMAIN.COM"
nginx    | 18.117.253.113 - - [14/Jul/2022:18:00:41 +0200] "GET /.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx    | 2022/07/14 18:00:41 [error] 26#26: *6 open() "/etc/nginx/html/.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y" failed (2: No such file or directory), client: 66.133.109.36, server: localhost, request: "GET /.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y HTTP/1.1", host: "kuma.MY-DOMAIN.COM"
nginx    | 66.133.109.36 - - [14/Jul/2022:18:00:41 +0200] "GET /.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
certbot  | Challenge failed for domain kuma.MY-DOMAIN.COM
certbot  | Challenge failed for domain www.kuma.MY-DOMAIN.COM
certbot  | 
certbot  | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
certbot  |   Domain: www.kuma.MY-DOMAIN.COM
certbot  |   Type:   dns
certbot  |   Detail: DNS problem: NXDOMAIN looking up A for www.kuma.MY-DOMAIN.COM - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.kuma.MY-DOMAIN.COM - check that a DNS record exists for this domain
certbot  | 
certbot  |   Domain: kuma.MY-DOMAIN.COM
certbot  |   Type:   unauthorized
certbot  |   Detail: 185.196.21.187: Invalid response from http://kuma.MY-DOMAIN.COM/.well-known/acme-challenge/iCXAiSi8IsX-viqida2bpdeDYvTGYDpdVs_rpvmIu2Y: 404
certbot  | 
certbot  | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
certbot  | 
certbot  | http-01 challenge for kuma.MY-DOMAIN.COM
certbot  | http-01 challenge for www.kuma.MY-DOMAIN.COM
certbot  | Cleaning up challenges
certbot  | Some challenges have failed.
certbot  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
certbot exited with code 0
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for MY-DOMAIN.COM
nginx    | Waiting for Let's Encrypt certificates for kuma.MY-DOMAIN.COM
....
```

___

My `compose.yaml`:

```yaml

services:
  nginx:
    container_name: nginx
    build: ./nginx-config # I renamed this folder (it's ok)
    env_file: config.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/var/www/static:ro
      - nginx_conf:/etc/nginx/sites
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./vhosts:/etc/nginx/vhosts
#      - ./html:/var/www/html. # <--- I don't have static webcontent. I have upstream (Maybe it should be /var/www/certbot?)
    restart: unless-stopped
    networks:
      - smz_default
      - nginx
      - monitoring

  certbot:
    build: ./certbot
#    image: evgeniy-khyst/certbot
    container_name: certbot
    env_file: config.env
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    networks:
      - nginx

  cron:
    build: ./cron
    container_name: cron
#    image: evgeniy-khyst/cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped
    networks:
      - nginx


networks:
  nginx:
    name: nginx
  smz_default:
    external: true
  monitoring:
    external: true

volumes:
  crowdsec-config:
  crowdsec-data:
  nginx_conf:
  letsencrypt_certs:
  certbot_acme_challenge:
  static:
    external: true
    name: smz_static

```

**Comment by evgeniy-khist** [comment]
@steklopod , have you already solved the issue?
You can add `upstream` to `nginx/site.conf.tpl` (before the first run) but you don't need `upstream` if you are forwarding requests to another Docker container. Just include Docker container name in the `proxy_pass` directive without delaring an `upstream`.
Here is an example: https://github.com/evgeniy-khist/letsencrypt-docker-compose#c156f4dfc046a4229590da3484f9478d
`upstream` is needed when we want Nginx to load-balance the requests among multiple servers. In Docker environment it is not needed.
Pay attention that host port should be omitted:
```yaml
services:
  my-backend:
    image: example.com/my-backend:1.0.0
    #...
    ports:
      - "8080"
```
This way you can scale the container: `docker-compose up -d --scale my-backend=2`.
